apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.ponzmild.net
spec:
  group: samplecontroller.ponzmild.net
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            deploymentName:
              format: string
              type: string
            replicas:
              format: int32
              minimum: 1
              type: integer
          required:
          - deploymentName
          - replicas
          type: object
        status:
          properties:
            availableReplicas:
              format: int32
              type: integer
          required:
          - availableReplicas
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
